Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.4"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true  # brings up the vm in gui window
    vb.memory = 2048
    vb.cpus = 2
  end

  # config.vm.provision "shell", path: "provision.sh"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "jenkins-docker"
  end
end

# Install Jenkins Manual steps
# sudo yum -y install java-1.8.0-openjdk epel-release
# sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
# sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
# sudo yum -y install jenkins-2.121.1
# sudo systemctl enable jenkins
# sudo systemctl start jenkins