# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'getoptlong'

opts = GetoptLong.new(
  [ '--install', GetoptLong::OPTIONAL_ARGUMENT ]
)

install=''

opts.each do |opt, arg|
  case opt
    when '--install'
      install=arg
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.hostname = "hiflexdev001"
  config.vm.network :private_network, ip: "192.168.16.25"
  config.vm.network "private_network", type: "dhcp"
  config.ssh.forward_agent = true
    config.vm.provider :virtualbox do |vb|
    vb.name = "hiflexdev001"
    vb.gui = true
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '4096',
      '--cpus', '2'
    ]
  end

  config.vm.provision "shell", path: "provision.sh"

  config.vm.provision :file, source: "runme.sh", destination: "/home/vagrant/runme.sh"
  config.vm.provision :file, source: "load-guest-additions.sh", destination: "/home/vagrant/load-guest-additions.sh"
  config.vm.provision :file, source: "load-vscode.sh", destination: "/home/vagrant/load-vscode.sh"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "st2-sandbox"
  end
end
