Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./cookbooks/dev/Berksfile"

  # config.vm.provision :chef_solo do |chef|
  # chef.run_list = [
  #   'recipe[php]'
  # ]

  # end
end